parameters:
#    quelp_connect.example.class: Quelp\ConnectBundle\Example
#    quelp_connect.example:
#        class: %quelp_connect.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    acme_user.registration.form.type:
        class: Quelp\ConnectBundle\Form\Type\RegistrationFormType
         #quelp_connect.example.class: Quelp\ConnectBundle\Controller\RegistrationController
        tags:
            - { name: form.type, alias: acme_user_registration }
