status:
    resource: "@StatusBundle/Resources/config/routing.yml"
    prefix:   /

quelp_relation:
    resource: "@QuelpRelationBundle/Resources/config/routing.yml"
    prefix:   /

quelp_image:
    resource: "@QuelpImageBundle/Resources/config/routing.yml"
    prefix:   /

backend_admin:
    resource: "@BackendAdminBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

quelp_connect:
    resource: "@QuelpConnectBundle/Resources/config/routing.yml"
    prefix:   /

quelp_message:
    resource: "@QuelpMessageBundle/Resources/config/routing.yml"
    prefix:   /

d_bdb:
    resource: "@DBdbBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

login_check:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

logout:
   pattern: /logout

infobundle:
  resource: "@QuelpInfosBundle/Resources/config/routing.yml"
  prefix: /