parameters:
#    quelp_image.example.class: Quelp\ImageBundle\Example

services:
#    quelp_image.example:
#        class: %quelp_image.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
