quelp_infos_apropospage:
     path:     /apropos
     defaults: { _controller: QuelpInfosBundle:Apropos:index }
quelp_infos_privacypolicy:
     path:     /privacypolicy
     defaults: { _controller: QuelpInfosBundle:Privacypolicy:index }
quelp_infos_termsofservice:
     path:     /termsofservice
     defaults: { _controller: QuelpInfosBundle:Termsofservice:index }