################################################################################################
#####################################   HOME MESSAGE   #########################################
################################################################################################

quelp_message_homepage:
    path:     /messages
    defaults: { _controller:QuelpMessageBundle:Message:index }

################################################################################################
#####################################   WRITE NEW MESSAGE   ####################################
################################################################################################

#quelp_message_newmessagepage:
 #   path:     /messages/new
  #  defaults: { _controller:QuelpMessageBundle:Message:newMessage }

quelp_message_friendmessagepage:
    path:     /messages/{name}
    defaults: { _controller:QuelpMessageBundle:Message:listMessage }

